add chakra box component
webzard-io/meta-ui pull request #21
Opened 2021-07-28 07:27 UTC by chenenpei

add chakra box to runtime components

2021-07-28 07:31 UTC, chenenpei commented on packages/runtime/src/components/chakra-ui/Box.tsx
> +      const raw = useExpression(value);
这个地方的解析感觉写的不太好。
如果 styleSchema 声明的字段不改变是没问题的。但如果遇到字段增删的场景，这里的 hook 调用会有影响吗？

2021-07-28 07:39 UTC, Yuyz0112 requested changes

2021-07-28 07:39 UTC, Yuyz0112 commented on packages/runtime/src/components/chakra-ui/Box.tsx
> +      const raw = useExpression(value);
原则上不应该是循环/条件判断里使用 hook，不过这个是 useExpression 的问题，可以先这样。

2021-07-28 07:39 UTC, Yuyz0112 commented on packages/runtime/src/components/chakra-ui/Box.tsx
> +          name: "styleScheme",
为什么需要多一层 styleScheme，而不是那些属性直接在一级？

2021-07-29 06:51 UTC, chenenpei commented on packages/runtime/src/components/chakra-ui/Box.tsx
> +          name: "styleScheme",
已调整。

2021-08-02 01:42 UTC, Yuyz0112 commented
good job

2021-08-02 01:42 UTC, Yuyz0112 approved these changes

2021-08-02 01:43 UTC, merged