impl number input component
webzard-io/meta-ui pull request #29
Opened 2021-08-04 01:37 UTC by jessie975

impl chakra-ui number input

2021-08-04 03:58 UTC, Yuyz0112 requested changes

2021-08-04 03:58 UTC, Yuyz0112 commented on packages/runtime/example/input-components/numberInput.html
> +                  type: "core/v1/state",
这个 state trait 起到什么作用？

2021-08-04 05:59 UTC, jessie975 commented on packages/runtime/example/input-components/numberInput.html
> +                  type: "core/v1/state",
发现是我理解错误了，想着他是一个带state的组件，所以在这里额外又补上了这个trait，刚才又捋了一下其实组件内部已经merge了他本身的value，所以这里应该不需要再重复使用了，已经删掉了~

2021-08-05 10:24 UTC, Yuyz0112 approved these changes

2021-08-05 10:24 UTC, merged